# Each new term in the Fibonacci sequence is generated by 
# adding the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose 
# values do not exceed four million, find the sum of 
# the even-valued terms.

x = [ 1, 2 ]

until x[-1] > 4_000_000
	fib = x[-2..-1]
	x << increment = fib.inject { |sum, x| sum + x }
end

y = x.select { |element| element % 2 == 0}

answer = y.inject { |sum, num| sum + num}

p x

puts

p y

puts

p answer





